### ISSUE TITLE
More explanation of PCA section

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/raster-time-series-alaska-lesson#4]
I already added some more text explaining what's going on in the PCA section but it is a little bit involved so more clarification should be added.

**Comment by qdread** [comment]
I put a few more clarifications in there and I think it's probably overkill to add too much more text. For now I will leave this open in case @andGarc you want to add anything else before closing.

**Comment by andGarc** [comment]
Added more clarification on bricks vs stacks.
