### ISSUE TITLE
potentially remove demo of the wrong way to do things 

### ISSUE THREAD

**Issue by reblake** [SESYNC-ci/raster-time-series-alaska-lesson#6]
In the Zonal Averages section, the code chunk demonstrating invalid geometries doesn't seem to serve a pedagogical purpose anymore.  Consider revising lesson to remove, or just have text explanation of the issue.

**Comment by andGarc** [comment]
I have revised the lesson and replaced the 'do not eval' section with a section on how to rasterized the vector shapefile.
