### ISSUE TITLE
Burn scar rasterize -- make it so it works

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/raster-time-series-alaska-lesson#7]
Right now the rasterize doesn't work on the burn  scar polygon b/c it generates invalid geometries. We should manually edit the burn scar polygon file so that it can produce a valid result when you run rasterize on it, so we can demonstrate it for people.

**Comment by andGarc** [comment]
I have included a fixed shapefile in the handouts.zip folder. It produces valid results and works when rasterized.  
We need to replace the contents in  `/nfs/public-data/trainingOVERLAY_ID_83_399_144_TEST_BURNT_83_144_399_reclassed` with the new fixed shapefile.

**Comment by andGarc** [comment]
New fixed shapefile can be found here `/nfs/public-data/training/OVERLAY_ID_83_399_144_TEST_BURNT_83_144_399_reclassed`.
The shapefiles in the handouts.zip has also been updated.
